# ----------------------------
# Makefile Options
# ----------------------------

NAME = MOUSE
ICON = icon.png
DESCRIPTION = "Avoid the cat!"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
